### PR TITLE
Added frontend buttons & draft docs

### LINKED ISSUE #21: Diagram Development and Refinement
### Diagram Development
- Complete and refine the following diagrams:
- Use Case Diagram
- Object Diagram
- Control Diagram
- Sequence Diagram
- State Diagram
          
### Focus Areas:
- Derive classes into objects and integrate them into the use case structure.
- Fixes & Cleanup
      
### Address any required fixes or improvements based on feedback.
- Optimize and organize the frontend diagram for clarity.
- Documentation

### Update the Word document to incorporate new features.

### LINKED ISSUE #22: Button Functionality Diagram and Documentation Updates
### Diagram Updates
- Update the diagram to reflect all button functionalities.

### Documentation
- Add relevant updates to the Word document to capture frontend changes.

### PR DESCRIPTION
**Pull request by crealol2**

### CODE REVIEW

**Review by NikitaKarim — APPROVED** [review]
### Project Manager Review: UI/UX and Functional Feedback

***1. Use Consistent Terms:***
_Issue_: The forms use both "Users" and "Professors," which could confuse users.  
_Suggestion_: Pick one term (either "Users" or "Professors") or use both consistently (e.g., "User/Professor Management") throughout the interface.

***2. User Permissions and Roles:***
 _Issue_:  
 The "Is Admin" checkbox is unclear about what it does.  
There’s no clear logic about what each role (like admin or regular user) can do.  
 _Suggestion_:  
 Add rules so users only see and do tasks that match their role.  
For example, only admins can add or remove classes.

***3. Navigation and User Feedback:***
 _Issue_:  
There are no messages when users make a mistake (like during login or adding a class). 
Users don’t get success or failure messages for actions (e.g., adding or deleting records).  
 _Suggestion_:  
Add error messages for invalid inputs and confirmation messages when actions are successful (e.g., "Class added successfully!").  

***4. Login Form Feedback:***
 _Issue_: Users don’t get a message when their login fails.  
 _Suggestion_: Add a message like "Invalid username or password" for failed login attempts. 

***5. Main Form Improvements:***
 _Issue_:  
It’s unclear if Add Class/Student saves records right away or after confirmation.  
 _Suggestion_:  
 Explain whether records are saved immediately or after confirmation.

***6. User/Professor Form Clarity:***
 _Issue_:  
It’s not clear if adding a professor automatically links them to a class.  
The meaning of "Courses" isn’t obvious – are they courses the professor teaches, takes, or manages?  
 _Suggestion_:  
Clearly state if adding a professor links them to classes.  
Explain what the "Courses" section represents.



***7. Consistent Confirmation Popups:***
 _Issue_: Some delete actions show a Yes/No confirmation, but others don’t.  
 _Suggestion_: Make sure all delete actions show the same confirmation popup to avoid mistakes.

**Comment by BobdaFett** [comment]
Reopening PR for extra review.

**Review by BobdaFett — CHANGES_REQUESTED** [review]
Refer to Nikita's review above.

**Review by Danises — COMMENTED** [review]
**Test Case:** Verify the Buttons Diagram and Buttons Functionality list for the Student Management System.

**Test ID:** TC-SMS-BDFL-001

**ID breakdown:**
- **TCD** - Prefix for "Test Case Document"
- **SMS** - Acronym for "Student Management System"
- **BDFL** - Acronym for "Button Diagrams and Functionality List"
- **001** - Version

**Environment:**  
- **Platform:** Windows 11  
- **Framework:** C# .NET 8.0  

**Attachments:**  
- `Frontend_Buttons.docx`
- `Frontend_Second_Draft.png`

**Summary:**  
Scenario outline, to ensure each button in the SMS is listed and their functions are well-defined.

**Expected & Actual Results**

1. **Login Form:**
   - **Expected:** Logs user and opens the main form.
   - **Actual:** The diagram and list show both functionalities.

2. **Main Form:**
   - **Expected:** Student search, add student, remove student, class search, add class, remove class, view professor, log out.
   - **Actual:** The diagram and list show all functionalities.

3. **Add Student Pop-up Form:**
   - **Expected:**
      - **Create:** Adds a student with the inputted data.
      - **Cancel:** Closes the pop-up and returns to the main form.
   - **Actual:** The diagram and list show both functionalities.

4. **Confirmation Pop-up (Student Removal):**
   - **Expected:**
      - **Yes:** Deletes the selected student(s) from the database.
      - **No:** Closes the confirmation pop-up without deleting.
   - **Actual:** The diagram and list confirm both functionalities.

5. **Add Class Pop-up Form:**
   - **Expected:**
      - **Create:** Adds a class with the inputted data.
      - **Cancel:** Closes the pop-up and returns to the main form.
   - **Actual:** The diagram and list show both functionalities.

6. **Confirmation Pop-up (Class Removal):**
   - **Expected:**
      - **Yes:** Deletes the selected class from the database.
      - **No:** Closes the confirmation pop-up without deleting.
   - **Actual:** The diagram and list confirm both functionalities.

7. **User/Professors Form:**
   - **Expected:** Allows viewing, adding, and removing users/professors.
   - **Actual:** The diagram and list show the form and its functionalities.

8. **Add User Pop-up Form:**
   - **Expected:**
      - **Create:** Adds a user with the inputted data.
      - **Cancel:** Closes the pop-up and returns to the User/Professors form.
   - **Actual:** The diagram and list show both functionalities.

9. **Confirmation Pop-up (User Removal):**
   - **Expected:**
      - **Yes:** Deletes the selected user(s) from the list.
      - **No:** Closes the confirmation pop-up without deleting.
   - **Actual:** The diagram and list confirm both functionalities.

10. **Close Button (User/Professors Form):**
    - **Expected:** Closes the User/Professors form and returns control to the main form.
    - **Actual:** The diagram and list show this functionality.

11. **Logout Button (Main Form):**
    - **Expected:** Logs the user out and returns to the login form.
    - **Actual:** The diagram and list confirm this functionality.

**Test Status:** Pass

**Reviewer:** Daniel Espin

**Comment by Jasnski** [comment]
Will look at this and see what I can do to add additional changes to the document

**Pull request merged**
